# Generated by Django 5.1.3 on 2024-12-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0002_tag_pack_cover_pack_slug_pack_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='sales_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
