# Generated by Django 5.1.3 on 2024-12-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0003_pack_sales_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pack',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='packs', to='pine.packitem'),
        ),
    ]
