# Generated by Django 5.1.3 on 2024-12-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0004_packitem_pack_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloademail',
            name='consent_for_marketing',
            field=models.BooleanField(default=False, verbose_name='Consentimento para marketing'),
        ),
        migrations.AddField(
            model_name='downloademail',
            name='found_us_through',
            field=models.CharField(choices=[('google', 'Google'), ('social_media', 'Mídias Sociais'), ('friend', 'Indicação de Amigo'), ('other', 'Outro')], default='', max_length=100, verbose_name='Por onde nos encontrou?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloademail',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem'),
        ),
        migrations.AddField(
            model_name='downloademail',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome completo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downloademail',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
