# Generated by Django 5.1.3 on 2024-12-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0005_downloademail_consent_for_marketing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloademail',
            name='message',
        ),
    ]
