# Generated by Django 5.1.3 on 2024-12-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0009_remove_creative_description_remove_creative_is_free_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='creative',
            name='carousels',
            field=models.ManyToManyField(blank=True, related_name='creatives', to='pine.carousel'),
        ),
    ]
