# Generated by Django 4.2.16 on 2025-01-10 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pine', '0011_carousel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='creative',
            name='name',
        ),
    ]
