name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        python manage.py migrate
      working-directory: pine_studio

    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput
      working-directory: pine_studio

    - name: Restart application
      run: |
        # Comando para reiniciar a aplicação, por exemplo, se estiver usando Gunicorn ou Docker
        # Exemplo de comando no servidor de produção
        sudo systemctl restart gunicorn
